name: Deploy Headlamp

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Install unzip (required for Helm setup)
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0 # Puedes cambiar la versión si lo deseas

      - name: Add Headlamp Helm repo
        run: helm repo add headlamp https://headlamp-k8s.github.io/headlamp

      - name: Update Helm repos
        run: helm repo update

      - name: Install/Upgrade Headlamp
        run: |
          helm upgrade --install headlamp headlamp/headlamp \
            -n headlamp \
            -f k8s/helm-values.yaml \
            --create-namespace
